name: botc_lights_app
description: BotC Lights App

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  app_settings: any
  bits: any
  collection: any
  flex_color_picker: any
  flutter_reactive_ble: any
  flutter_riverpod: any
  permission_handler: any
  shared_preferences: any

dev_dependencies:
  flutter_launcher_icons: any
  flutter_lints: any

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  macos:
    generate: true
  image_path: assets/icons/icon.png

flutter:
  uses-material-design: true
